[tool.pytest.ini_options]
addopts = "-s --disable-pytest-warnings"

[tool.coverage.run]
source = ["bot"]

[tool.black]
line-length = 120
exclude = '''
/(
    \.deployment
)/
'''

[tool.isort]
profile = "black"
skip = ["__init__.py", ".deployment/"]

[tool.mypy]
ignore_missing_imports = true
exclude = ["local/", ".deployment/"]
