[default]
env_verbose_name = "Not set"
base_backend_url = "http://127.0.0.1:8000"
should_load_ssm_parameters = true

# Logging
indent_json = false
std_formatter = "json"
root_log_level = "DEBUG"
bot_log_level = "INFO"

[test]
env_verbose_name = "Test"
should_load_ssm_parameters = false
std_formatter = "debug"
telegram_token = "12345:DUMMY_TOKEN"

[local]
env_verbose_name = "Local"
should_load_ssm_parameters = false
std_formatter = "simple"
bot_log_level = "DEBUG"
persistence_db_table_name = "the-spymaster-bot-dev-persistence-table"

[dev]
env_verbose_name = "Dev"
base_backend_url = "https://backend.dev.303707.xyz"

[stage]
env_verbose_name = "Staging"

[prod]
env_verbose_name = "Production"
base_backend_url = "https://backend.303707.xyz"

[rsbpi]
env_verbose_name = "Raspberry Pi"
base_backend_url = "http://192.168.1.240:8000"
