name: Delivery

on:
  push:

jobs:

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          make install-ci
          make install-test
      - name: Run tests
        run: |
          make test

  deploy-dev:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs:
      - unit-tests
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Deploy to dev
        uses: .github/actions/deploy
        with:
          workspace: default
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          sentry_dsn: ${{ secrets.DEFAULT_SENTRY_DSN }}
          telegram_token: ${{ secrets.DEFAULT_TELEGRAM_TOKEN }}

  automation:
    runs-on: ubuntu-latest
    needs:
      - deploy-dev
    steps:
      - name: Checkout automation repo
        uses: actions/checkout@master
        with:
          repository: asaf-kali/the-spymaster-automation
          token: ${{ secrets.AUTOMATION_REPO_PAT }}
          path: automation
      - name: Set up python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install CI dependencies
        run: cd automation; make install-ci
      - name: Install dependencies
        run: cd automation; make install-test
      - name: Run automation
        run: cd automation; make test
