name: Deploy

on:
  workflow_run:
    workflows: [ "tests" ]
    branches: [ not-main ]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Deploy service to AWS
        run: |
          cd tf; terraform init
          make deploy
