name: Development

on:
  push:

jobs:
  local-development:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Init local development environment
        run: |
          make install-ci
          make install SYNC=""
